// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: groups.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const addGroupMember = `-- name: AddGroupMember :one
INSERT INTO group_members (group_id, user_id, is_admin)
VALUES ($1, $2, $3)
ON CONFLICT (group_id, user_id) DO NOTHING
RETURNING id, group_id, user_id, is_admin, joined_at
`

type AddGroupMemberParams struct {
	GroupID uuid.UUID `json:"group_id"`
	UserID  uuid.UUID `json:"user_id"`
	IsAdmin bool      `json:"is_admin"`
}

func (q *Queries) AddGroupMember(ctx context.Context, arg AddGroupMemberParams) (GroupMember, error) {
	row := q.db.QueryRowContext(ctx, addGroupMember, arg.GroupID, arg.UserID, arg.IsAdmin)
	var i GroupMember
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.UserID,
		&i.IsAdmin,
		&i.JoinedAt,
	)
	return i, err
}

const createGroup = `-- name: CreateGroup :one
INSERT INTO groups (name, created_by)
VALUES ($1, $2)
RETURNING id, name, created_by, created_at
`

type CreateGroupParams struct {
	Name      string    `json:"name"`
	CreatedBy uuid.UUID `json:"created_by"`
}

func (q *Queries) CreateGroup(ctx context.Context, arg CreateGroupParams) (Group, error) {
	row := q.db.QueryRowContext(ctx, createGroup, arg.Name, arg.CreatedBy)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const createGroupInvite = `-- name: CreateGroupInvite :one
INSERT INTO group_invites (group_id, token, created_by, expires_at)
VALUES ($1, $2, $3, NOW() + INTERVAL '7 days')
ON CONFLICT (group_id) DO UPDATE
  SET token = EXCLUDED.token,
      created_by = EXCLUDED.created_by,
      created_at = NOW(),
      expires_at = NOW() + INTERVAL '7 days'
RETURNING id, group_id, token, created_by, created_at, expires_at
`

type CreateGroupInviteParams struct {
	GroupID   uuid.UUID `json:"group_id"`
	Token     string    `json:"token"`
	CreatedBy uuid.UUID `json:"created_by"`
}

func (q *Queries) CreateGroupInvite(ctx context.Context, arg CreateGroupInviteParams) (GroupInvite, error) {
	row := q.db.QueryRowContext(ctx, createGroupInvite, arg.GroupID, arg.Token, arg.CreatedBy)
	var i GroupInvite
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.Token,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getGroupByID = `-- name: GetGroupByID :one
SELECT id, name, created_by, created_at FROM groups WHERE id = $1
`

func (q *Queries) GetGroupByID(ctx context.Context, id uuid.UUID) (Group, error) {
	row := q.db.QueryRowContext(ctx, getGroupByID, id)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getGroupInvite = `-- name: GetGroupInvite :one
SELECT id, group_id, token, created_by, created_at, expires_at FROM group_invites WHERE group_id = $1
`

func (q *Queries) GetGroupInvite(ctx context.Context, groupID uuid.UUID) (GroupInvite, error) {
	row := q.db.QueryRowContext(ctx, getGroupInvite, groupID)
	var i GroupInvite
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.Token,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getGroupInviteByToken = `-- name: GetGroupInviteByToken :one
SELECT gi.id, gi.group_id, gi.token, gi.created_by, gi.created_at, gi.expires_at, g.name as group_name
FROM group_invites gi
JOIN groups g ON g.id = gi.group_id
WHERE gi.token = $1 AND gi.expires_at > NOW()
`

type GetGroupInviteByTokenRow struct {
	ID        uuid.UUID `json:"id"`
	GroupID   uuid.UUID `json:"group_id"`
	Token     string    `json:"token"`
	CreatedBy uuid.UUID `json:"created_by"`
	CreatedAt time.Time `json:"created_at"`
	ExpiresAt time.Time `json:"expires_at"`
	GroupName string    `json:"group_name"`
}

func (q *Queries) GetGroupInviteByToken(ctx context.Context, token string) (GetGroupInviteByTokenRow, error) {
	row := q.db.QueryRowContext(ctx, getGroupInviteByToken, token)
	var i GetGroupInviteByTokenRow
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.Token,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.GroupName,
	)
	return i, err
}

const getGroupMember = `-- name: GetGroupMember :one
SELECT id, group_id, user_id, is_admin, joined_at FROM group_members WHERE group_id = $1 AND user_id = $2
`

type GetGroupMemberParams struct {
	GroupID uuid.UUID `json:"group_id"`
	UserID  uuid.UUID `json:"user_id"`
}

func (q *Queries) GetGroupMember(ctx context.Context, arg GetGroupMemberParams) (GroupMember, error) {
	row := q.db.QueryRowContext(ctx, getGroupMember, arg.GroupID, arg.UserID)
	var i GroupMember
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.UserID,
		&i.IsAdmin,
		&i.JoinedAt,
	)
	return i, err
}

const isGroupAdmin = `-- name: IsGroupAdmin :one
SELECT is_admin FROM group_members WHERE group_id = $1 AND user_id = $2
`

type IsGroupAdminParams struct {
	GroupID uuid.UUID `json:"group_id"`
	UserID  uuid.UUID `json:"user_id"`
}

func (q *Queries) IsGroupAdmin(ctx context.Context, arg IsGroupAdminParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, isGroupAdmin, arg.GroupID, arg.UserID)
	var is_admin bool
	err := row.Scan(&is_admin)
	return is_admin, err
}

const listGroupMembers = `-- name: ListGroupMembers :many
SELECT gm.id, gm.group_id, gm.user_id, gm.is_admin, gm.joined_at, u.email, u.display_name, u.photo_path
FROM group_members gm
JOIN users u ON u.id = gm.user_id
WHERE gm.group_id = $1
ORDER BY gm.joined_at ASC
`

type ListGroupMembersRow struct {
	ID          uuid.UUID `json:"id"`
	GroupID     uuid.UUID `json:"group_id"`
	UserID      uuid.UUID `json:"user_id"`
	IsAdmin     bool      `json:"is_admin"`
	JoinedAt    time.Time `json:"joined_at"`
	Email       string    `json:"email"`
	DisplayName string    `json:"display_name"`
	PhotoPath   string    `json:"photo_path"`
}

func (q *Queries) ListGroupMembers(ctx context.Context, groupID uuid.UUID) ([]ListGroupMembersRow, error) {
	rows, err := q.db.QueryContext(ctx, listGroupMembers, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListGroupMembersRow
	for rows.Next() {
		var i ListGroupMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.UserID,
			&i.IsAdmin,
			&i.JoinedAt,
			&i.Email,
			&i.DisplayName,
			&i.PhotoPath,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserGroups = `-- name: ListUserGroups :many
SELECT g.id, g.name, g.created_by, g.created_at, gm.is_admin
FROM groups g
JOIN group_members gm ON gm.group_id = g.id
WHERE gm.user_id = $1
ORDER BY g.created_at DESC
`

type ListUserGroupsRow struct {
	ID        uuid.UUID `json:"id"`
	Name      string    `json:"name"`
	CreatedBy uuid.UUID `json:"created_by"`
	CreatedAt time.Time `json:"created_at"`
	IsAdmin   bool      `json:"is_admin"`
}

func (q *Queries) ListUserGroups(ctx context.Context, userID uuid.UUID) ([]ListUserGroupsRow, error) {
	rows, err := q.db.QueryContext(ctx, listUserGroups, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserGroupsRow
	for rows.Next() {
		var i ListUserGroupsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.IsAdmin,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const promoteMemberToAdmin = `-- name: PromoteMemberToAdmin :exec
UPDATE group_members SET is_admin = TRUE
WHERE group_id = $1 AND user_id = $2
`

type PromoteMemberToAdminParams struct {
	GroupID uuid.UUID `json:"group_id"`
	UserID  uuid.UUID `json:"user_id"`
}

func (q *Queries) PromoteMemberToAdmin(ctx context.Context, arg PromoteMemberToAdminParams) error {
	_, err := q.db.ExecContext(ctx, promoteMemberToAdmin, arg.GroupID, arg.UserID)
	return err
}
