// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: magic_links.sql

package db

import (
	"context"
)

const createMagicLink = `-- name: CreateMagicLink :one
INSERT INTO magic_links (email, token, redirect_path)
VALUES ($1, $2, $3)
RETURNING id, email, token, redirect_path, created_at, expires_at, used_at
`

type CreateMagicLinkParams struct {
	Email        string `json:"email"`
	Token        string `json:"token"`
	RedirectPath string `json:"redirect_path"`
}

func (q *Queries) CreateMagicLink(ctx context.Context, arg CreateMagicLinkParams) (MagicLink, error) {
	row := q.db.QueryRowContext(ctx, createMagicLink, arg.Email, arg.Token, arg.RedirectPath)
	var i MagicLink
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Token,
		&i.RedirectPath,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.UsedAt,
	)
	return i, err
}

const getMagicLinkByToken = `-- name: GetMagicLinkByToken :one
SELECT id, email, token, redirect_path, created_at, expires_at, used_at FROM magic_links
WHERE token = $1 AND expires_at > NOW() AND used_at IS NULL
`

func (q *Queries) GetMagicLinkByToken(ctx context.Context, token string) (MagicLink, error) {
	row := q.db.QueryRowContext(ctx, getMagicLinkByToken, token)
	var i MagicLink
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Token,
		&i.RedirectPath,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.UsedAt,
	)
	return i, err
}

const markMagicLinkUsed = `-- name: MarkMagicLinkUsed :exec
UPDATE magic_links SET used_at = NOW() WHERE token = $1
`

func (q *Queries) MarkMagicLinkUsed(ctx context.Context, token string) error {
	_, err := q.db.ExecContext(ctx, markMagicLinkUsed, token)
	return err
}
