// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: matches.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createMatch = `-- name: CreateMatch :one
INSERT INTO matches (phase, match_number, group_name, home_team, away_team, match_time, stadium, city, day_number)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, phase, match_number, group_name, home_team, away_team, match_time, stadium, city, day_number, home_score, away_score, is_finished, has_extra_time, created_at
`

type CreateMatchParams struct {
	Phase       string       `json:"phase"`
	MatchNumber int32        `json:"match_number"`
	GroupName   string       `json:"group_name"`
	HomeTeam    string       `json:"home_team"`
	AwayTeam    string       `json:"away_team"`
	MatchTime   sql.NullTime `json:"match_time"`
	Stadium     string       `json:"stadium"`
	City        string       `json:"city"`
	DayNumber   int32        `json:"day_number"`
}

func (q *Queries) CreateMatch(ctx context.Context, arg CreateMatchParams) (Match, error) {
	row := q.db.QueryRowContext(ctx, createMatch,
		arg.Phase,
		arg.MatchNumber,
		arg.GroupName,
		arg.HomeTeam,
		arg.AwayTeam,
		arg.MatchTime,
		arg.Stadium,
		arg.City,
		arg.DayNumber,
	)
	var i Match
	err := row.Scan(
		&i.ID,
		&i.Phase,
		&i.MatchNumber,
		&i.GroupName,
		&i.HomeTeam,
		&i.AwayTeam,
		&i.MatchTime,
		&i.Stadium,
		&i.City,
		&i.DayNumber,
		&i.HomeScore,
		&i.AwayScore,
		&i.IsFinished,
		&i.HasExtraTime,
		&i.CreatedAt,
	)
	return i, err
}

const getMatchByID = `-- name: GetMatchByID :one
SELECT id, phase, match_number, group_name, home_team, away_team, match_time, stadium, city, day_number, home_score, away_score, is_finished, has_extra_time, created_at FROM matches WHERE id = $1
`

func (q *Queries) GetMatchByID(ctx context.Context, id uuid.UUID) (Match, error) {
	row := q.db.QueryRowContext(ctx, getMatchByID, id)
	var i Match
	err := row.Scan(
		&i.ID,
		&i.Phase,
		&i.MatchNumber,
		&i.GroupName,
		&i.HomeTeam,
		&i.AwayTeam,
		&i.MatchTime,
		&i.Stadium,
		&i.City,
		&i.DayNumber,
		&i.HomeScore,
		&i.AwayScore,
		&i.IsFinished,
		&i.HasExtraTime,
		&i.CreatedAt,
	)
	return i, err
}

const getMatchDayWeight = `-- name: GetMatchDayWeight :one
SELECT weight FROM match_day_weights WHERE day_number = $1
`

func (q *Queries) GetMatchDayWeight(ctx context.Context, dayNumber int32) (int32, error) {
	row := q.db.QueryRowContext(ctx, getMatchDayWeight, dayNumber)
	var weight int32
	err := row.Scan(&weight)
	return weight, err
}

const listAllMatches = `-- name: ListAllMatches :many
SELECT id, phase, match_number, group_name, home_team, away_team, match_time, stadium, city, day_number, home_score, away_score, is_finished, has_extra_time, created_at FROM matches ORDER BY match_time ASC, match_number ASC
`

func (q *Queries) ListAllMatches(ctx context.Context) ([]Match, error) {
	rows, err := q.db.QueryContext(ctx, listAllMatches)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Match
	for rows.Next() {
		var i Match
		if err := rows.Scan(
			&i.ID,
			&i.Phase,
			&i.MatchNumber,
			&i.GroupName,
			&i.HomeTeam,
			&i.AwayTeam,
			&i.MatchTime,
			&i.Stadium,
			&i.City,
			&i.DayNumber,
			&i.HomeScore,
			&i.AwayScore,
			&i.IsFinished,
			&i.HasExtraTime,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFinishedUnscored = `-- name: ListFinishedUnscored :many
SELECT m.id, m.phase, m.match_number, m.group_name, m.home_team, m.away_team, m.match_time, m.stadium, m.city, m.day_number, m.home_score, m.away_score, m.is_finished, m.has_extra_time, m.created_at FROM matches m
WHERE m.is_finished = TRUE
  AND m.id NOT IN (SELECT DISTINCT match_id FROM scores)
ORDER BY m.match_time ASC
`

func (q *Queries) ListFinishedUnscored(ctx context.Context) ([]Match, error) {
	rows, err := q.db.QueryContext(ctx, listFinishedUnscored)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Match
	for rows.Next() {
		var i Match
		if err := rows.Scan(
			&i.ID,
			&i.Phase,
			&i.MatchNumber,
			&i.GroupName,
			&i.HomeTeam,
			&i.AwayTeam,
			&i.MatchTime,
			&i.Stadium,
			&i.City,
			&i.DayNumber,
			&i.HomeScore,
			&i.AwayScore,
			&i.IsFinished,
			&i.HasExtraTime,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMatchesByPhase = `-- name: ListMatchesByPhase :many
SELECT id, phase, match_number, group_name, home_team, away_team, match_time, stadium, city, day_number, home_score, away_score, is_finished, has_extra_time, created_at FROM matches WHERE phase = $1 ORDER BY match_time ASC, match_number ASC
`

func (q *Queries) ListMatchesByPhase(ctx context.Context, phase string) ([]Match, error) {
	rows, err := q.db.QueryContext(ctx, listMatchesByPhase, phase)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Match
	for rows.Next() {
		var i Match
		if err := rows.Scan(
			&i.ID,
			&i.Phase,
			&i.MatchNumber,
			&i.GroupName,
			&i.HomeTeam,
			&i.AwayTeam,
			&i.MatchTime,
			&i.Stadium,
			&i.City,
			&i.DayNumber,
			&i.HomeScore,
			&i.AwayScore,
			&i.IsFinished,
			&i.HasExtraTime,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOpenForPrediction = `-- name: ListOpenForPrediction :many
SELECT id, phase, match_number, group_name, home_team, away_team, match_time, stadium, city, day_number, home_score, away_score, is_finished, has_extra_time, created_at FROM matches
WHERE match_time > NOW() AND is_finished = FALSE
  AND home_team != '' AND away_team != ''
ORDER BY match_time ASC
`

func (q *Queries) ListOpenForPrediction(ctx context.Context) ([]Match, error) {
	rows, err := q.db.QueryContext(ctx, listOpenForPrediction)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Match
	for rows.Next() {
		var i Match
		if err := rows.Scan(
			&i.ID,
			&i.Phase,
			&i.MatchNumber,
			&i.GroupName,
			&i.HomeTeam,
			&i.AwayTeam,
			&i.MatchTime,
			&i.Stadium,
			&i.City,
			&i.DayNumber,
			&i.HomeScore,
			&i.AwayScore,
			&i.IsFinished,
			&i.HasExtraTime,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUpcomingMatches = `-- name: ListUpcomingMatches :many
SELECT id, phase, match_number, group_name, home_team, away_team, match_time, stadium, city, day_number, home_score, away_score, is_finished, has_extra_time, created_at FROM matches
WHERE match_time > NOW() AND home_team != '' AND away_team != ''
ORDER BY match_time ASC
LIMIT $1
`

func (q *Queries) ListUpcomingMatches(ctx context.Context, limit int32) ([]Match, error) {
	rows, err := q.db.QueryContext(ctx, listUpcomingMatches, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Match
	for rows.Next() {
		var i Match
		if err := rows.Scan(
			&i.ID,
			&i.Phase,
			&i.MatchNumber,
			&i.GroupName,
			&i.HomeTeam,
			&i.AwayTeam,
			&i.MatchTime,
			&i.Stadium,
			&i.City,
			&i.DayNumber,
			&i.HomeScore,
			&i.AwayScore,
			&i.IsFinished,
			&i.HasExtraTime,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setMatchResult = `-- name: SetMatchResult :one
UPDATE matches
SET home_score = $2, away_score = $3, is_finished = TRUE, has_extra_time = $4
WHERE id = $1
RETURNING id, phase, match_number, group_name, home_team, away_team, match_time, stadium, city, day_number, home_score, away_score, is_finished, has_extra_time, created_at
`

type SetMatchResultParams struct {
	ID           uuid.UUID     `json:"id"`
	HomeScore    sql.NullInt32 `json:"home_score"`
	AwayScore    sql.NullInt32 `json:"away_score"`
	HasExtraTime bool          `json:"has_extra_time"`
}

func (q *Queries) SetMatchResult(ctx context.Context, arg SetMatchResultParams) (Match, error) {
	row := q.db.QueryRowContext(ctx, setMatchResult,
		arg.ID,
		arg.HomeScore,
		arg.AwayScore,
		arg.HasExtraTime,
	)
	var i Match
	err := row.Scan(
		&i.ID,
		&i.Phase,
		&i.MatchNumber,
		&i.GroupName,
		&i.HomeTeam,
		&i.AwayTeam,
		&i.MatchTime,
		&i.Stadium,
		&i.City,
		&i.DayNumber,
		&i.HomeScore,
		&i.AwayScore,
		&i.IsFinished,
		&i.HasExtraTime,
		&i.CreatedAt,
	)
	return i, err
}

const updateMatchTeams = `-- name: UpdateMatchTeams :exec
UPDATE matches SET home_team = $2, away_team = $3 WHERE id = $1
`

type UpdateMatchTeamsParams struct {
	ID       uuid.UUID `json:"id"`
	HomeTeam string    `json:"home_team"`
	AwayTeam string    `json:"away_team"`
}

func (q *Queries) UpdateMatchTeams(ctx context.Context, arg UpdateMatchTeamsParams) error {
	_, err := q.db.ExecContext(ctx, updateMatchTeams, arg.ID, arg.HomeTeam, arg.AwayTeam)
	return err
}

const upsertMatchDayWeight = `-- name: UpsertMatchDayWeight :exec
INSERT INTO match_day_weights (day_number, match_date, weight)
VALUES ($1, $2, $3)
ON CONFLICT (day_number) DO UPDATE SET match_date = EXCLUDED.match_date, weight = EXCLUDED.weight
`

type UpsertMatchDayWeightParams struct {
	DayNumber int32     `json:"day_number"`
	MatchDate time.Time `json:"match_date"`
	Weight    int32     `json:"weight"`
}

func (q *Queries) UpsertMatchDayWeight(ctx context.Context, arg UpsertMatchDayWeightParams) error {
	_, err := q.db.ExecContext(ctx, upsertMatchDayWeight, arg.DayNumber, arg.MatchDate, arg.Weight)
	return err
}
