// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Group struct {
	ID        uuid.UUID `json:"id"`
	Name      string    `json:"name"`
	CreatedBy uuid.UUID `json:"created_by"`
	CreatedAt time.Time `json:"created_at"`
}

type GroupInvite struct {
	ID        uuid.UUID `json:"id"`
	GroupID   uuid.UUID `json:"group_id"`
	Token     string    `json:"token"`
	CreatedBy uuid.UUID `json:"created_by"`
	CreatedAt time.Time `json:"created_at"`
	ExpiresAt time.Time `json:"expires_at"`
}

type GroupMember struct {
	ID       uuid.UUID `json:"id"`
	GroupID  uuid.UUID `json:"group_id"`
	UserID   uuid.UUID `json:"user_id"`
	IsAdmin  bool      `json:"is_admin"`
	JoinedAt time.Time `json:"joined_at"`
}

type MagicLink struct {
	ID           uuid.UUID    `json:"id"`
	Email        string       `json:"email"`
	Token        string       `json:"token"`
	RedirectPath string       `json:"redirect_path"`
	CreatedAt    time.Time    `json:"created_at"`
	ExpiresAt    time.Time    `json:"expires_at"`
	UsedAt       sql.NullTime `json:"used_at"`
}

type Match struct {
	ID           uuid.UUID     `json:"id"`
	Phase        string        `json:"phase"`
	MatchNumber  int32         `json:"match_number"`
	GroupName    string        `json:"group_name"`
	HomeTeam     string        `json:"home_team"`
	AwayTeam     string        `json:"away_team"`
	MatchTime    sql.NullTime  `json:"match_time"`
	Stadium      string        `json:"stadium"`
	City         string        `json:"city"`
	DayNumber    int32         `json:"day_number"`
	HomeScore    sql.NullInt32 `json:"home_score"`
	AwayScore    sql.NullInt32 `json:"away_score"`
	IsFinished   bool          `json:"is_finished"`
	HasExtraTime bool          `json:"has_extra_time"`
	CreatedAt    time.Time     `json:"created_at"`
}

type MatchDayWeight struct {
	DayNumber int32     `json:"day_number"`
	MatchDate time.Time `json:"match_date"`
	Weight    int32     `json:"weight"`
}

type Prediction struct {
	ID        uuid.UUID `json:"id"`
	UserID    uuid.UUID `json:"user_id"`
	MatchID   uuid.UUID `json:"match_id"`
	HomeScore int32     `json:"home_score"`
	AwayScore int32     `json:"away_score"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type Score struct {
	ID          uuid.UUID `json:"id"`
	UserID      uuid.UUID `json:"user_id"`
	MatchID     uuid.UUID `json:"match_id"`
	RawPoints   int32     `json:"raw_points"`
	DayWeight   int32     `json:"day_weight"`
	TotalPoints int32     `json:"total_points"`
	Criterion   string    `json:"criterion"`
	ComputedAt  time.Time `json:"computed_at"`
}

type Session struct {
	ID        uuid.UUID `json:"id"`
	UserID    uuid.UUID `json:"user_id"`
	Token     string    `json:"token"`
	CreatedAt time.Time `json:"created_at"`
	ExpiresAt time.Time `json:"expires_at"`
}

type User struct {
	ID           uuid.UUID `json:"id"`
	Email        string    `json:"email"`
	DisplayName  string    `json:"display_name"`
	PhotoPath    string    `json:"photo_path"`
	IsSuperadmin bool      `json:"is_superadmin"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}
