// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: scores.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const globalRanking = `-- name: GlobalRanking :many
SELECT u.id, u.display_name, u.photo_path,
       COALESCE(SUM(s.total_points), 0) as total_points,
       COUNT(s.id) as predictions_scored,
       RANK() OVER (ORDER BY COALESCE(SUM(s.total_points), 0) DESC) as rank
FROM users u
LEFT JOIN scores s ON s.user_id = u.id
GROUP BY u.id, u.display_name, u.photo_path
ORDER BY total_points DESC, u.display_name ASC
`

type GlobalRankingRow struct {
	ID                uuid.UUID   `json:"id"`
	DisplayName       string      `json:"display_name"`
	PhotoPath         string      `json:"photo_path"`
	TotalPoints       interface{} `json:"total_points"`
	PredictionsScored int64       `json:"predictions_scored"`
	Rank              int64       `json:"rank"`
}

func (q *Queries) GlobalRanking(ctx context.Context) ([]GlobalRankingRow, error) {
	rows, err := q.db.QueryContext(ctx, globalRanking)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GlobalRankingRow
	for rows.Next() {
		var i GlobalRankingRow
		if err := rows.Scan(
			&i.ID,
			&i.DisplayName,
			&i.PhotoPath,
			&i.TotalPoints,
			&i.PredictionsScored,
			&i.Rank,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const groupRanking = `-- name: GroupRanking :many
SELECT u.id, u.display_name, u.photo_path, gm.is_admin,
       COALESCE(SUM(s.total_points), 0) as total_points,
       RANK() OVER (ORDER BY COALESCE(SUM(s.total_points), 0) DESC) as rank
FROM group_members gm
JOIN users u ON u.id = gm.user_id
LEFT JOIN scores s ON s.user_id = gm.user_id
WHERE gm.group_id = $1
GROUP BY u.id, u.display_name, u.photo_path, gm.is_admin
ORDER BY total_points DESC, u.display_name ASC
`

type GroupRankingRow struct {
	ID          uuid.UUID   `json:"id"`
	DisplayName string      `json:"display_name"`
	PhotoPath   string      `json:"photo_path"`
	IsAdmin     bool        `json:"is_admin"`
	TotalPoints interface{} `json:"total_points"`
	Rank        int64       `json:"rank"`
}

func (q *Queries) GroupRanking(ctx context.Context, groupID uuid.UUID) ([]GroupRankingRow, error) {
	rows, err := q.db.QueryContext(ctx, groupRanking, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GroupRankingRow
	for rows.Next() {
		var i GroupRankingRow
		if err := rows.Scan(
			&i.ID,
			&i.DisplayName,
			&i.PhotoPath,
			&i.IsAdmin,
			&i.TotalPoints,
			&i.Rank,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertScore = `-- name: UpsertScore :exec
INSERT INTO scores (user_id, match_id, raw_points, day_weight, total_points, criterion)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (user_id, match_id) DO UPDATE
  SET raw_points = EXCLUDED.raw_points,
      day_weight = EXCLUDED.day_weight,
      total_points = EXCLUDED.total_points,
      criterion = EXCLUDED.criterion,
      computed_at = NOW()
`

type UpsertScoreParams struct {
	UserID      uuid.UUID `json:"user_id"`
	MatchID     uuid.UUID `json:"match_id"`
	RawPoints   int32     `json:"raw_points"`
	DayWeight   int32     `json:"day_weight"`
	TotalPoints int32     `json:"total_points"`
	Criterion   string    `json:"criterion"`
}

func (q *Queries) UpsertScore(ctx context.Context, arg UpsertScoreParams) error {
	_, err := q.db.ExecContext(ctx, upsertScore,
		arg.UserID,
		arg.MatchID,
		arg.RawPoints,
		arg.DayWeight,
		arg.TotalPoints,
		arg.Criterion,
	)
	return err
}

const userTotalScore = `-- name: UserTotalScore :one
SELECT COALESCE(SUM(s.total_points), 0) as total_points
FROM scores s
WHERE s.user_id = $1
`

func (q *Queries) UserTotalScore(ctx context.Context, userID uuid.UUID) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, userTotalScore, userID)
	var total_points interface{}
	err := row.Scan(&total_points)
	return total_points, err
}
