// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*) FROM users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, display_name, photo_path, is_superadmin)
VALUES ($1, $2, $3, $4)
RETURNING id, email, display_name, photo_path, is_superadmin, created_at, updated_at
`

type CreateUserParams struct {
	Email        string `json:"email"`
	DisplayName  string `json:"display_name"`
	PhotoPath    string `json:"photo_path"`
	IsSuperadmin bool   `json:"is_superadmin"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.Email,
		arg.DisplayName,
		arg.PhotoPath,
		arg.IsSuperadmin,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.PhotoPath,
		&i.IsSuperadmin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFirstUser = `-- name: GetFirstUser :one
SELECT id, email, display_name, photo_path, is_superadmin, created_at, updated_at FROM users ORDER BY created_at ASC LIMIT 1
`

func (q *Queries) GetFirstUser(ctx context.Context) (User, error) {
	row := q.db.QueryRowContext(ctx, getFirstUser)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.PhotoPath,
		&i.IsSuperadmin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, display_name, photo_path, is_superadmin, created_at, updated_at FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.PhotoPath,
		&i.IsSuperadmin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, display_name, photo_path, is_superadmin, created_at, updated_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.PhotoPath,
		&i.IsSuperadmin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users SET display_name = $2, photo_path = $3, updated_at = NOW()
WHERE id = $1
RETURNING id, email, display_name, photo_path, is_superadmin, created_at, updated_at
`

type UpdateUserParams struct {
	ID          uuid.UUID `json:"id"`
	DisplayName string    `json:"display_name"`
	PhotoPath   string    `json:"photo_path"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUser, arg.ID, arg.DisplayName, arg.PhotoPath)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.PhotoPath,
		&i.IsSuperadmin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
